// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsADXjnjR0Wv0pnl2rzmONBwoSvE7TJs',
    appId: '1:274043185653:android:420c97396b4c89f8b798bc',
    messagingSenderId: '274043185653',
    projectId: 'elminiawypatisserie',
    storageBucket: 'elminiawypatisserie.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl5i5kApdp7TcuG-FiGjUNgHtq4yZip7U',
    appId: '1:274043185653:web:9b8db796289dfd48b798bc',
    messagingSenderId: '274043185653',
    projectId: 'elminiawypatisserie',
    authDomain: 'elminiawypatisserie.firebaseapp.com',
    storageBucket: 'elminiawypatisserie.firebasestorage.app',
    measurementId: 'G-76WJF9W886',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHPMWPoo68t2m8dLyjDtd35M7ZEU_3ljY',
    appId: '1:274043185653:ios:decdc423b8c71a63b798bc',
    messagingSenderId: '274043185653',
    projectId: 'elminiawypatisserie',
    storageBucket: 'elminiawypatisserie.firebasestorage.app',
    androidClientId: '274043185653-72gv74mo06f2rd05tl1rbq5bojqqn1h1.apps.googleusercontent.com',
    iosClientId: '274043185653-k472rdd680q17456co1474m2j0mh2nn7.apps.googleusercontent.com',
    iosBundleId: 'com.coder.driver',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHPMWPoo68t2m8dLyjDtd35M7ZEU_3ljY',
    appId: '1:274043185653:ios:decdc423b8c71a63b798bc',
    messagingSenderId: '274043185653',
    projectId: 'elminiawypatisserie',
    storageBucket: 'elminiawypatisserie.firebasestorage.app',
    androidClientId: '274043185653-72gv74mo06f2rd05tl1rbq5bojqqn1h1.apps.googleusercontent.com',
    iosClientId: '274043185653-k472rdd680q17456co1474m2j0mh2nn7.apps.googleusercontent.com',
    iosBundleId: 'com.coder.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl5i5kApdp7TcuG-FiGjUNgHtq4yZip7U',
    appId: '1:274043185653:web:3f86f41cbd4943dbb798bc',
    messagingSenderId: '274043185653',
    projectId: 'elminiawypatisserie',
    authDomain: 'elminiawypatisserie.firebaseapp.com',
    storageBucket: 'elminiawypatisserie.firebasestorage.app',
    measurementId: 'G-YDZH4NYQ7D',
  );

}